use_frameworks!

target 'MVImagePicker_Example' do
    pod "JTSImageViewController", "~> 1.5"
    pod 'MVImagePicker', :path => '../'
    pod "SVProgressHUD", "~> 1.1"

    target 'MVImagePicker_Tests' do
        inherit! :search_paths
    end
end
